version: "3.8"

services:
    # Pasos antes del build
    # 1. Descomentar solo el target que se va a utilizar.
    # 2. Si se usa una imagen CPU comentar deploy y devices con anidados.

    backend:
        container_name: backend-tesis
        build:
            context: ./backend
            target: CPU
            #target: GPU
        ports:
            - "8080:8080"
        volumes:
            - ./backend/src:/src
        env_file:
            - ./backend/.env
        stdin_open: true # docker run -i
        tty: true # docker run -t
        #devices:
        #  - /dev/bus/usb:/dev/bus/usb
        #  - /dev/video0:/dev/video0
        #deploy:
        #    resources:
        #        reservations:
        #            devices:
        #                - capabilities: [ gpu ]

    frontend:
        container_name: frontend-tesis
        build:
            context: ./frontend
        ports:
            - 80:80
            - 4200:4200
        volumes:
            - ./frontend:/app
            - /app/node_modules #Ignorar el directorio node_modules para evitar errores
