name: Continuous Integration Main

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Python Blacken  
        uses: piotrpawlaczek/python-blacken@release/stable
        with:
          line-length: '110'
          path: 'backend/src'
